package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/tagpro/itineraries/server/internal/domain"
	"github.com/tagpro/itineraries/server/internal/store/queries"
)

// SQL is a Store over database/sql, with every statement generated by sqlc
// from queries.sql. It is written against the SQLite dialect and works
// unchanged on Cloudflare D1 (through the workers-go driver) and on a
// local SQLite file (in tests). It uses no transactions, because D1 offers
// none; every statement is atomic on its own and the merge rule makes the
// sequence safe to interleave or repeat.
type SQL struct {
	q *queries.Queries
}

var _ Store = (*SQL)(nil)

func NewSQL(db *sql.DB) *SQL { return &SQL{q: queries.New(db)} }

func (s *SQL) CreateTrip(ctx context.Context, t domain.Trip) error {
	if _, err := s.GetTrip(ctx, t.ID); err == nil {
		return ErrTripExists
	} else if !errors.Is(err, ErrNotFound) {
		return err
	}
	return s.q.CreateTrip(ctx, queries.CreateTripParams{
		ID:        t.ID,
		Name:      t.Name,
		TokenHash: t.TokenHash,
		CreatedAt: t.CreatedAt.UnixMilli(),
	})
}

func (s *SQL) GetTrip(ctx context.Context, id string) (domain.Trip, error) {
	row, err := s.q.GetTrip(ctx, id)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.Trip{}, ErrNotFound
	}
	if err != nil {
		return domain.Trip{}, err
	}
	return tripFromRow(row), nil
}

func (s *SQL) ListTrips(ctx context.Context) ([]domain.Trip, error) {
	rows, err := s.q.ListTrips(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]domain.Trip, 0, len(rows))
	for _, r := range rows {
		out = append(out, tripFromRow(r))
	}
	return out, nil
}

func (s *SQL) SetTokenHash(ctx context.Context, id, hash string) error {
	n, err := s.q.SetTokenHash(ctx, queries.SetTokenHashParams{TokenHash: hash, ID: id})
	if err != nil {
		return err
	}
	if n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *SQL) GetState(ctx context.Context, tripID string) (domain.TripState, error) {
	if _, err := s.GetTrip(ctx, tripID); err != nil {
		return nil, err
	}
	rows, err := s.q.ListEntries(ctx, tripID)
	if err != nil {
		return nil, err
	}
	out := domain.TripState{}
	for _, r := range rows {
		if out[r.ListID] == nil {
			out[r.ListID] = domain.ListState{}
		}
		out[r.ListID][r.Key] = entryFrom(r.Value, r.UpdatedAt, r.Deleted)
	}
	return out, nil
}

func (s *SQL) GetList(ctx context.Context, tripID, listID string) (domain.ListState, error) {
	if _, err := s.GetTrip(ctx, tripID); err != nil {
		return nil, err
	}
	rows, err := s.q.ListEntriesInList(ctx, queries.ListEntriesInListParams{TripID: tripID, ListID: listID})
	if err != nil {
		return nil, err
	}
	out := domain.ListState{}
	for _, r := range rows {
		out[r.Key] = entryFrom(r.Value, r.UpdatedAt, r.Deleted)
	}
	return out, nil
}

// mergeRow is one element of the JSON array MergeEntries unpacks with
// json_each. V holds the entry's JSON as text, so that json_extract hands
// it back verbatim whatever its type.
type mergeRow struct {
	K string `json:"k"`
	V string `json:"v"`
	T int64  `json:"t"`
	D int64  `json:"d"`
}

// Merge hands the whole batch to the database as one statement; the
// ON CONFLICT clause in queries.sql applies domain.Wins to every row.
func (s *SQL) Merge(ctx context.Context, tripID, listID string, incoming domain.ListState) error {
	if _, err := s.GetTrip(ctx, tripID); err != nil {
		return err
	}
	if len(incoming) == 0 {
		return nil
	}
	rows := make([]mergeRow, 0, len(incoming))
	for k, e := range incoming {
		r := mergeRow{K: k, V: string(e.Value), T: e.Updated}
		if e.Deleted {
			r.D = 1
		}
		rows = append(rows, r)
	}
	payload, err := json.Marshal(rows)
	if err != nil {
		return err
	}
	if err := s.q.MergeEntries(ctx, queries.MergeEntriesParams{
		TripID:  tripID,
		ListID:  listID,
		Entries: string(payload),
	}); err != nil {
		return fmt.Errorf("merge %s/%s: %w", tripID, listID, err)
	}
	return nil
}

func tripFromRow(r queries.Trip) domain.Trip {
	return domain.Trip{
		ID:        r.ID,
		Name:      r.Name,
		TokenHash: r.TokenHash,
		CreatedAt: time.UnixMilli(r.CreatedAt).UTC(),
	}
}

func entryFrom(value string, updated, deleted int64) domain.Entry {
	return domain.Entry{Value: []byte(value), Updated: updated, Deleted: deleted != 0}
}
