// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type Entry struct {
	TripID    string
	ListID    string
	Key       string
	Value     string
	UpdatedAt int64
	Deleted   int64
}

type Trip struct {
	ID        string
	Name      string
	TokenHash string
	CreatedAt int64
}
