// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const createTrip = `-- name: CreateTrip :exec

INSERT INTO trips (id, name, token_hash, created_at)
VALUES (?, ?, ?, ?)
`

type CreateTripParams struct {
	ID        string
	Name      string
	TokenHash string
	CreatedAt int64
}

// Every statement the SQL store runs. sqlc compiles these against the
// schema in migrations/ into internal/store/queries; nothing in Go
// builds SQL from strings.
func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) error {
	_, err := q.db.ExecContext(ctx, createTrip,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.CreatedAt,
	)
	return err
}

const getTrip = `-- name: GetTrip :one
SELECT id, name, token_hash, created_at
FROM trips
WHERE id = ?
`

func (q *Queries) GetTrip(ctx context.Context, id string) (Trip, error) {
	row := q.db.QueryRowContext(ctx, getTrip, id)
	var i Trip
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT list_id, key, value, updated_at, deleted
FROM entries
WHERE trip_id = ?
`

type ListEntriesRow struct {
	ListID    string
	Key       string
	Value     string
	UpdatedAt int64
	Deleted   int64
}

func (q *Queries) ListEntries(ctx context.Context, tripID string) ([]ListEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesRow{}
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(
			&i.ListID,
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesInList = `-- name: ListEntriesInList :many
SELECT key, value, updated_at, deleted
FROM entries
WHERE trip_id = ? AND list_id = ?
`

type ListEntriesInListParams struct {
	TripID string
	ListID string
}

type ListEntriesInListRow struct {
	Key       string
	Value     string
	UpdatedAt int64
	Deleted   int64
}

func (q *Queries) ListEntriesInList(ctx context.Context, arg ListEntriesInListParams) ([]ListEntriesInListRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesInList, arg.TripID, arg.ListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesInListRow{}
	for rows.Next() {
		var i ListEntriesInListRow
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrips = `-- name: ListTrips :many
SELECT id, name, token_hash, created_at
FROM trips
ORDER BY created_at, id
`

func (q *Queries) ListTrips(ctx context.Context) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTrips)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeEntries = `-- name: MergeEntries :exec
INSERT INTO entries (trip_id, list_id, key, value, updated_at, deleted)
SELECT
  CAST(?1 AS TEXT),
  CAST(?2 AS TEXT),
  json_extract(j.value, '$.k'),
  json_extract(j.value, '$.v'),
  json_extract(j.value, '$.t'),
  json_extract(j.value, '$.d')
FROM json_each(CAST(?3 AS TEXT)) AS j
WHERE true
ON CONFLICT (trip_id, list_id, key) DO UPDATE SET
  value      = excluded.value,
  updated_at = excluded.updated_at,
  deleted    = excluded.deleted
WHERE excluded.updated_at > entries.updated_at
   OR (excluded.updated_at = entries.updated_at AND excluded.deleted > entries.deleted)
   OR (excluded.updated_at = entries.updated_at AND excluded.deleted = entries.deleted AND excluded.value > entries.value)
`

type MergeEntriesParams struct {
	TripID  string
	ListID  string
	Entries string
}

// MergeEntries is the whole merge rule in one statement. The caller passes
// the incoming entries as a JSON array - [{"k":...,"v":"<json text>","t":...,"d":0|1}, ...]
// - and json_each() turns it into rows, so any number of entries is one
// round trip and three bound parameters. That matters on D1, where each
// statement is a separate call and the free plan caps them per request.
//
// The ON CONFLICT clause mirrors domain.Wins term for term: a later stamp
// wins; on an equal stamp a tombstone wins; on an equal stamp and tombstone
// the greater value wins. "WHERE true" is required by SQLite's parser to
// disambiguate the upsert from a join ON clause after a SELECT, and the
// CASTs are what let sqlc type the parameters as strings.
func (q *Queries) MergeEntries(ctx context.Context, arg MergeEntriesParams) error {
	_, err := q.db.ExecContext(ctx, mergeEntries, arg.TripID, arg.ListID, arg.Entries)
	return err
}

const setTokenHash = `-- name: SetTokenHash :execrows
UPDATE trips SET token_hash = ? WHERE id = ?
`

type SetTokenHashParams struct {
	TokenHash string
	ID        string
}

func (q *Queries) SetTokenHash(ctx context.Context, arg SetTokenHashParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTokenHash, arg.TokenHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
